{
    "status": 200,
    "success": true,
    "message": "Imóvel atualizado com sucesso",
    "data": {
        "_id": "67f6ef52bbb18c501a8865db",
        "AnoConstrucao": "2010",
        "AreaPrivativa": "152",
        "AreaTotal": "0",
        "Bairro": "Itaim Bibi",
        "BairroComercial": "Itaim Bibi",
        "Banheiro7": "0",
        "Banheiro8": "0",
        "BanheiroSocialQtd": "4",
        "Banheiros1": "0",
        "Banheiros2": "0",
        "Banheiros3": "0",
        "Banheiros4": "0",
        "Banheiros5": "0",
        "Banheiros6": "0",
        "Bloco": "",
        "CEP": "04532-040",
        "Categoria": "Apartamento",
        "CategoriaDois": "",
        "CategoriaTres": "",
        "Cidade": "São Paulo",
        "Codigo": "173",
        "Complemento": "",
        "Construtora": "Lindenberg",
        "DataEntrega": "31/01/2010",
        "DataHoraAtualizacao": "2024-12-16 16:13:59",
        "DescricaoDiferenciais": "O condomínio Lindenberg Id Itaim foi construído em 2010 (há 12 anos)pela empresa Lindenberg. O condomínio residencial Lindenberg Id Itaim é composto por uma torre única,  é apropriado para quem busca lazer sem sair de casa e fica localizado em Rua Benedito Lapin no bairro Vila Olímpia em São Paulo.",
        "DescricaoUnidades": "Elegante apartamento no coração do Itaim Bibi com 152 m², 3 suítes e 3 vagas, que oferecem o máximo de conforto para você e sua família!\r\n\r\nA sala de estar espaçosa é dividida em dois ambientes, apresenta um planejamento inteligente na área de jantar e um elegante painel na sala de estar, com uma linda varanda gourmet, completamente fechada com vidros e jardim vertical que empresta uma atmosfera acolhedora ao ambiente. Equipado com sistema de som ambiente, receptor e TV, o apartamento ostenta piso em madeira e ar condicionado em todos os cômodos.\r\n\r\nCom três suítes elegantemente decoradas, dotadas de armários planejados, um lavabo e um hall social privativo, este espaço oferece conforto e privacidade em cada detalhe. A cozinha, completamente equipada e integrada à sala. Além disso, conta com uma área de serviço completa, incluindo dependência para funcionária. O apartamento dispõe ainda de três vagas de garagem e um depósito privativo para sua conveniência.\r\n\r\nO Lindenberg Id Itaim oferece uma ampla gama de opções de lazer para todos os gostos e idades, incluindo uma piscina coberta e aquecida, academia, sauna, piscina infantil, playground, brinquedoteca, espaço de coworking, sala de reunião e um salão de festas para celebrar momentos especiais.\r\n\r\nA localização é excepcional, com proximidade a várias comodidades, como o Hospital Sancta Maggiore, o Grupo Escolar Martim Francisco, o DeRose Method Itaim, a Escola Estadual Ludovina Credidio Peixoto, a Escola Lourenço Castanho e a Praça Pereira Coutinho. Além disso, o bairro oferece uma variedade de restaurantes e cafés que complementam a vida urbana.\r\n\r\nVenha agendar sua visita o quanto antes!\r\n\r\nEdificio Lindenberg Id Itaim - Itaim Bibi\r\nCondomínio Edifício Lindenberg Id Itaim\r\nCondomínio Lindenberg Id Itaim - Rua Benedito Lapin, 197\r\nR. Benedito Lapin, 197 - Itaim BibiSão Paulo - SP, 04532-040",
        "DestaquesDiferenciais": "Piscina\r\nArmário \r\nBanheiro\r\nDespensa\r\nSala\r\nChurrasqueira\r\nSauna\r\nElevador Privativo\r\nAr-Condicionado\r\nArmário na Área de Serviço\r\nLavanderia\r\nCozinha\r\nArmário no Quarto\r\nArmário Cozinha\r\nCloset\r\nTaco de madeira\r\nAquecimento Elétrico\r\nSala de estar\r\nArmário Suíte\r\nSala de Jantar\r\nAndar Alto",
        "DestaquesLazer": "No ID Lindenberg temos Lazer com Churrasqueira, Espaço Gourmet, Espaço Zen, Esquina, Jardim, Piscina, Piscina Aquecida, Piscina Infantil, Playground, Sala De Ginástica, Salão De Festa, Salão De Jogos, Sauna e Vestiário.",
        "DestaquesLocalizacao": "Localizado na zona oeste da cidade de São Paulo, o Itaim Bibi é um excelente lugar para morar, trabalhar ou mesmo passear. Com uma área de quase 10km2 e 81.730 moradores, o bairro é rico em lojas comerciais, boa gastronomia e atrações culturais, além de ter fácil acesso pelas avenidas Nações Unidas, Brigadeiro Faria Lima, Nove de Julho, Cidade Jardim, São Gabriel e Presidente Juscelino Kubitschek.\r\n\r\nEdificio Lindenberg Id Itaim - Itaim Bibi\r\nCondomínio Edifício Lindenberg Id Itaim\r\nCondomínio Lindenberg Id Itaim - Rua Benedito Lapin, 197\r\nR. Benedito Lapin, 197 - Itaim BibiSão Paulo - SP, 04532-040",
        "Dormitorio2": "0",
        "Dormitorio3": "0",
        "Dormitorio4": "0",
        "Dormitorio5": "0",
        "Dormitorio6": "0",
        "Dormitorio7": "0",
        "Dormitorio8": "0",
        "Dormitorios": "3",
        "DormitoriosAntigo": "3",
        "Empreendimento": "Lindenberg Id Itaim",
        "Endereco": "Benedito Lapin",
        "FaixaPreco1": "t) Consulte",
        "FaixaPreco2": "",
        "FaixaPreco3": "",
        "FaixaPreco4": "",
        "FaixaPreco5": "",
        "FaixaPreco6": "",
        "FaixaPreco7": "",
        "FaixaPreco8": "",
        "FichaTecnica": "Construção..................2010\r\nRealização................Lindenberg\r\nTorres..........................1\r\nMetragens ( m² ).........151m² a 244m²",
        "FinalidadeStatus": {
            "VENDA": true
        },
        "Foto": [
            {
                "Codigo": "photo-1753903409611-0",
                "FotoPequena": "https://cdn.vistahost.com.br/npinegoc/vista.imobi/fotos/381/iOU8s9Y1_38165f374bd4b1ee_p.jpg",
                "Foto": "https://npi-imoveis.s3.sa-east-1.amazonaws.com/imagens_baixadas/iOU8s9Y1_38165f374bd4b1ee.jpg",
                "Destaque": "Nao",
                "Tipo": "",
                "Descricao": "",
                "Ordem": 1
            },
            {
                "Codigo": "photo-1753903409611-1",
                "FotoPequena": "https://cdn.vistahost.com.br/npinegoc/vista.imobi/fotos/381/iOU8s9Y1_38165f374bf30a3c_p.jpg",
                "Foto": "https://npi-imoveis.s3.sa-east-1.amazonaws.com/imagens_baixadas/iOU8s9Y1_38165f374bf30a3c.jpg",
                "Destaque": "Nao",
                "Tipo": "",
                "Descricao": "",
                "Ordem": 2
            },
            {
                "Codigo": "photo-1753903409611-2",
                "FotoPequena": "https://cdn.vistahost.com.br/npinegoc/vista.imobi/fotos/381/iOU8s9Y1_38165f374c148c3d_p.jpg",
                "Foto": "https://npi-imoveis.s3.sa-east-1.amazonaws.com/imagens_baixadas/iOU8s9Y1_38165f374c148c3d.jpg",
                "Destaque": "Nao",
                "Tipo": "",
                "Descricao": "",
                "Ordem": 3
            },
            {
                "Codigo": "photo-1753903409611-3",
                "FotoPequena": "https://cdn.vistahost.com.br/npinegoc/vista.imobi/fotos/381/iOU8s9Y1_38165f374c373cd0_p.jpg",
                "Foto": "https://npi-imoveis.s3.sa-east-1.amazonaws.com/imagens_baixadas/iOU8s9Y1_38165f374c373cd0.jpg",
                "Destaque": "Nao",
                "Tipo": "",
                "Descricao": "",
                "Ordem": 4
            },
            {
                "Codigo": "photo-1753903409611-4",
                "FotoPequena": "https://cdn.vistahost.com.br/npinegoc/vista.imobi/fotos/381/iOU8s9Y1_38165f374c582f87_p.jpg",
                "Foto": "https://npi-imoveis.s3.sa-east-1.amazonaws.com/imagens_baixadas/iOU8s9Y1_38165f374c582f87.jpg",
                "Destaque": "Nao",
                "Tipo": "",
                "Descricao": "",
                "Ordem": 5
            },
            {
                "Codigo": "photo-1753903409611-5",
                "FotoPequena": "https://cdn.vistahost.com.br/npinegoc/vista.imobi/fotos/381/i57i56Wg14cV3Jqzg72_38166c3766fd42c6_p.jpg",
                "Foto": "https://npi-imoveis.s3.sa-east-1.amazonaws.com/imagens_baixadas/i57i56Wg14cV3Jqzg72_38166c3766fd42c6.jpg",
                "Destaque": "Nao",
                "Tipo": "",
                "Descricao": "",
                "Ordem": 6
            },
            {
                "Codigo": "photo-1753903409611-6",
                "FotoPequena": "https://cdn.vistahost.com.br/npinegoc/vista.imobi/fotos/381/i57i56Wg14cV3Jqzg72_38166c37671e780e_p.jpg",
                "Foto": "https://npi-imoveis.s3.sa-east-1.amazonaws.com/imagens_baixadas/i57i56Wg14cV3Jqzg72_38166c37671e780e.jpg",
                "Destaque": "Nao",
                "Tipo": "",
                "Descricao": "",
                "Ordem": 7
            },
            {
                "Codigo": "photo-1753903409611-7",
                "FotoPequena": "https://cdn.vistahost.com.br/npinegoc/vista.imobi/fotos/381/i57i56Wg14cV3Jqzg72_38166c37673ef60c_p.jpg",
                "Foto": "https://npi-imoveis.s3.sa-east-1.amazonaws.com/imagens_baixadas/i57i56Wg14cV3Jqzg72_38166c37673ef60c.jpg",
                "Destaque": "Nao",
                "Tipo": "",
                "Descricao": "",
                "Ordem": 8
            },
            {
                "Codigo": "photo-1753903409611-8",
                "FotoPequena": "https://cdn.vistahost.com.br/npinegoc/vista.imobi/fotos/381/i57i56Wg14cV3Jqzg72_38166c3767618258_p.jpg",
                "Foto": "https://npi-imoveis.s3.sa-east-1.amazonaws.com/imagens_baixadas/i57i56Wg14cV3Jqzg72_38166c3767618258.jpg",
                "Destaque": "Sim",
                "Tipo": "",
                "Descricao": "",
                "Ordem": 9
            },
            {
                "Codigo": "photo-1753903409611-9",
                "FotoPequena": "https://cdn.vistahost.com.br/npinegoc/vista.imobi/fotos/381/i57i56Wg14cV3Jqzg72_38166c37678144a0_p.jpg",
                "Foto": "https://npi-imoveis.s3.sa-east-1.amazonaws.com/imagens_baixadas/i57i56Wg14cV3Jqzg72_38166c37678144a0.jpg",
                "Destaque": "Nao",
                "Tipo": "",
                "Descricao": "",
                "Ordem": 10
            },
            {
                "Codigo": "photo-1753903409611-10",
                "FotoPequena": "https://cdn.vistahost.com.br/npinegoc/vista.imobi/fotos/381/i57i56Wg14cV3Jqzg72_38166c37679e53ca_p.jpg",
                "Foto": "https://npi-imoveis.s3.sa-east-1.amazonaws.com/imagens_baixadas/i57i56Wg14cV3Jqzg72_38166c37679e53ca.jpg",
                "Destaque": "Nao",
                "Tipo": "",
                "Descricao": "",
                "Ordem": 11
            },
            {
                "Codigo": "photo-1753903409611-11",
                "FotoPequena": "https://cdn.vistahost.com.br/npinegoc/vista.imobi/fotos/381/i57i56Wg14cV3Jqzg72_38166c3767c1d909_p.jpg",
                "Foto": "https://npi-imoveis.s3.sa-east-1.amazonaws.com/imagens_baixadas/i57i56Wg14cV3Jqzg72_38166c3767c1d909.jpg",
                "Destaque": "Nao",
                "Tipo": "",
                "Descricao": "",
                "Ordem": 12
            },
            {
                "Codigo": "photo-1753903409611-12",
                "FotoPequena": "https://cdn.vistahost.com.br/npinegoc/vista.imobi/fotos/381/i57i56Wg14cV3Jqzg72_38166c3767e1eae3_p.jpg",
                "Foto": "https://npi-imoveis.s3.sa-east-1.amazonaws.com/imagens_baixadas/i57i56Wg14cV3Jqzg72_38166c3767e1eae3.jpg",
                "Destaque": "Nao",
                "Tipo": "",
                "Descricao": "",
                "Ordem": 13
            },
            {
                "Codigo": "photo-1753903409611-13",
                "FotoPequena": "https://cdn.vistahost.com.br/npinegoc/vista.imobi/fotos/381/i57i56Wg14cV3Jqzg72_38166c37680376d6_p.jpg",
                "Foto": "https://npi-imoveis.s3.sa-east-1.amazonaws.com/imagens_baixadas/i57i56Wg14cV3Jqzg72_38166c37680376d6.jpg",
                "Destaque": "Nao",
                "Tipo": "",
                "Descricao": "",
                "Ordem": 14
            },
            {
                "Codigo": "photo-1753903409611-14",
                "FotoPequena": "https://cdn.vistahost.com.br/npinegoc/vista.imobi/fotos/381/i57i56Wg14cV3Jqzg72_38166c376824fbce_p.jpg",
                "Foto": "https://npi-imoveis.s3.sa-east-1.amazonaws.com/imagens_baixadas/i57i56Wg14cV3Jqzg72_38166c376824fbce.jpg",
                "Destaque": "Nao",
                "Tipo": "",
                "Descricao": "",
                "Ordem": 15
            },
            {
                "Codigo": "photo-1753903409611-15",
                "FotoPequena": "https://cdn.vistahost.com.br/npinegoc/vista.imobi/fotos/381/i57i56Wg14cV3Jqzg72_38166c3768427ac5_p.jpg",
                "Foto": "https://npi-imoveis.s3.sa-east-1.amazonaws.com/imagens_baixadas/i57i56Wg14cV3Jqzg72_38166c3768427ac5.jpg",
                "Destaque": "Nao",
                "Tipo": "",
                "Descricao": "",
                "Ordem": 16
            },
            {
                "Codigo": "photo-1753903409611-16",
                "FotoPequena": "https://cdn.vistahost.com.br/npinegoc/vista.imobi/fotos/381/i57i56Wg14cV3Jqzg72_38166c37686034f9_p.jpg",
                "Foto": "https://npi-imoveis.s3.sa-east-1.amazonaws.com/imagens_baixadas/i57i56Wg14cV3Jqzg72_38166c37686034f9.jpg",
                "Destaque": "Nao",
                "Tipo": "",
                "Descricao": "",
                "Ordem": 17
            },
            {
                "Codigo": "photo-1753903409611-17",
                "FotoPequena": "https://cdn.vistahost.com.br/npinegoc/vista.imobi/fotos/381/i57i56Wg14cV3Jqzg72_38166c376881049d_p.jpg",
                "Foto": "https://npi-imoveis.s3.sa-east-1.amazonaws.com/imagens_baixadas/i57i56Wg14cV3Jqzg72_38166c376881049d.jpg",
                "Destaque": "Nao",
                "Tipo": "",
                "Descricao": "",
                "Ordem": 18
            },
            {
                "Codigo": "photo-1753903409611-18",
                "FotoPequena": "https://cdn.vistahost.com.br/npinegoc/vista.imobi/fotos/381/i57i56Wg14cV3Jqzg72_38166c37689d3218_p.jpg",
                "Foto": "https://npi-imoveis.s3.sa-east-1.amazonaws.com/imagens_baixadas/i57i56Wg14cV3Jqzg72_38166c37689d3218.jpg",
                "Destaque": "Nao",
                "Tipo": "",
                "Descricao": "",
                "Ordem": 19
            },
            {
                "Codigo": "photo-1753903409611-19",
                "FotoPequena": "https://cdn.vistahost.com.br/npinegoc/vista.imobi/fotos/381/i57i56Wg14cV3Jqzg72_38166c3768c09ca9_p.jpg",
                "Foto": "https://npi-imoveis.s3.sa-east-1.amazonaws.com/imagens_baixadas/i57i56Wg14cV3Jqzg72_38166c3768c09ca9.jpg",
                "Destaque": "Nao",
                "Tipo": "",
                "Descricao": "",
                "Ordem": 20
            },
            {
                "Codigo": "photo-1753903409611-20",
                "FotoPequena": "https://cdn.vistahost.com.br/npinegoc/vista.imobi/fotos/381/i57i56Wg14cV3Jqzg72_38166c3768e0fd06_p.jpg",
                "Foto": "https://npi-imoveis.s3.sa-east-1.amazonaws.com/imagens_baixadas/i57i56Wg14cV3Jqzg72_38166c3768e0fd06.jpg",
                "Destaque": "Nao",
                "Tipo": "",
                "Descricao": "",
                "Ordem": 21
            },
            {
                "Codigo": "photo-1753903409611-21",
                "FotoPequena": "https://cdn.vistahost.com.br/npinegoc/vista.imobi/fotos/381/i57i56Wg14cV3Jqzg72_38166c3768fe1eef_p.jpg",
                "Foto": "https://npi-imoveis.s3.sa-east-1.amazonaws.com/imagens_baixadas/i57i56Wg14cV3Jqzg72_38166c3768fe1eef.jpg",
                "Destaque": "Nao",
                "Tipo": "",
                "Descricao": "",
                "Ordem": 22
            },
            {
                "Codigo": "photo-1753903409611-22",
                "FotoPequena": "https://cdn.vistahost.com.br/npinegoc/vista.imobi/fotos/381/i57i56Wg14cV3Jqzg72_38166c37691dd2b3_p.jpg",
                "Foto": "https://npi-imoveis.s3.sa-east-1.amazonaws.com/imagens_baixadas/i57i56Wg14cV3Jqzg72_38166c37691dd2b3.jpg",
                "Destaque": "Nao",
                "Tipo": "",
                "Descricao": "",
                "Ordem": 23
            },
            {
                "Codigo": "photo-1753903409611-23",
                "FotoPequena": "https://cdn.vistahost.com.br/npinegoc/vista.imobi/fotos/381/i57i56Wg14cV3Jqzg72_38166c37693f247c_p.jpg",
                "Foto": "https://npi-imoveis.s3.sa-east-1.amazonaws.com/imagens_baixadas/i57i56Wg14cV3Jqzg72_38166c37693f247c.jpg",
                "Destaque": "Nao",
                "Tipo": "",
                "Descricao": "",
                "Ordem": 24
            },
            {
                "Codigo": "photo-1753903409611-24",
                "FotoPequena": "https://cdn.vistahost.com.br/npinegoc/vista.imobi/fotos/381/i57i56Wg14cV3Jqzg72_38166c37695d06f7_p.jpg",
                "Foto": "https://npi-imoveis.s3.sa-east-1.amazonaws.com/imagens_baixadas/i57i56Wg14cV3Jqzg72_38166c37695d06f7.jpg",
                "Destaque": "Nao",
                "Tipo": "",
                "Descricao": "",
                "Ordem": 25
            },
            {
                "Codigo": "photo-1753903409611-25",
                "FotoPequena": "https://cdn.vistahost.com.br/npinegoc/vista.imobi/fotos/381/i57i56Wg14cV3Jqzg72_38166c37697abac7_p.jpg",
                "Foto": "https://npi-imoveis.s3.sa-east-1.amazonaws.com/imagens_baixadas/i57i56Wg14cV3Jqzg72_38166c37697abac7.jpg",
                "Destaque": "Nao",
                "Tipo": "",
                "Descricao": "",
                "Ordem": 26
            },
            {
                "Codigo": "photo-1753903409611-26",
                "FotoPequena": "https://cdn.vistahost.com.br/npinegoc/vista.imobi/fotos/381/i57i56Wg14cV3Jqzg72_38166c37699a8df5_p.jpg",
                "Foto": "https://npi-imoveis.s3.sa-east-1.amazonaws.com/imagens_baixadas/i57i56Wg14cV3Jqzg72_38166c37699a8df5.jpg",
                "Destaque": "Nao",
                "Tipo": "",
                "Descricao": "",
                "Ordem": 27
            },
            {
                "Codigo": "photo-1753903409611-27",
                "FotoPequena": "https://cdn.vistahost.com.br/npinegoc/vista.imobi/fotos/381/i57i56Wg14cV3Jqzg72_38166c3769b93fe6_p.jpg",
                "Foto": "https://npi-imoveis.s3.sa-east-1.amazonaws.com/imagens_baixadas/i57i56Wg14cV3Jqzg72_38166c3769b93fe6.jpg",
                "Destaque": "Nao",
                "Tipo": "",
                "Descricao": "",
                "Ordem": 28
            }
        ],
        "FotoEmpreendimento": [],
        "Latitude": "-23.5874583",
        "Longitude": "-46.6736216",
        "Metragem1": "f) 151 m² a 180 m²",
        "Metragem2": "",
        "Metragem3": "",
        "Metragem4": "",
        "Metragem5": "",
        "Metragem6": "",
        "Metragem7": "",
        "Metragem8": "",
        "MetragemAnt": "152",
        "MetragemAnt2": "",
        "MetragemAnt3": "",
        "MetragemAnt4": "",
        "MetragemAnt5": "",
        "MetragemAnt6": "",
        "MetragemAnt7": "",
        "MetragemAnt8": "",
        "Numero": "197",
        "Situacao": "PRONTO USADO",
        "Status": "VENDA",
        "SuiteAntigo": "3",
        "Suites": "3",
        "Suites2": "0",
        "Suites3": "0",
        "Suites4": "0",
        "Suites5": "0",
        "Suites6": "0",
        "Suites7": "0",
        "Suites8": "0",
        "TipoEndereco": "Rua",
        "TituloSite": "Lindenberg ID Itaim - Apartamento no Itaim | NPi Imóveis.",
        "Tour360": "",
        "UF": "SP",
        "Vagas": "3",
        "Vagas1": "0",
        "Vagas2": "0",
        "Vagas3": "0",
        "Vagas4": "0",
        "Vagas5": "0",
        "Vagas6": "0",
        "Vagas7": "0",
        "Vagas8": "0",
        "VagasAntigo": "3",
        "ValorAluguel2": "0",
        "ValorAluguel3": "0",
        "ValorAluguel5": "0",
        "ValorAluguel6": "0",
        "ValorAluguel7": "0",
        "ValorAluguel8": "0",
        "ValorAluguelSite": "",
        "ValorAluguel_4": "0",
        "ValorAntigo": "4.250.000",
        "ValorCobertura": "0",
        "ValorCobertura2": "0",
        "ValorCondominio": "3571",
        "ValorDiaria": "0",
        "ValorGarden": "0",
        "ValorGarden2": "0",
        "ValorIptu": "1004",
        "ValorLocacao": "",
        "ValorVenda": "4250000",
        "ValorVenda2": "0",
        "ValorVenda3": "0",
        "ValorVenda4": "0",
        "Video": [],
        "Slug": "lindenberg-id-itaim",
        "Condominio": "Sim",
        "Ativo": "Sim",
        "CondominioDestaque": "Não",
        "Automacao": false,
        "updatedAt": "2025-07-30T19:23:47.800Z"
    }
}
